#pragma once
#include "stdfix.h"

typedef std::vector<pair<int, int>> vecPairInt;

typedef struct WD {
	char16_t vBuf[ROWS][COLS]{ 0 };
	int grid[ROWS][COLS]{ 0 };
} wd;

enum Colors {
	White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	Red = FOREGROUND_RED,
	Green = FOREGROUND_GREEN,
	Blue = FOREGROUND_BLUE,
	Cyan = FOREGROUND_GREEN | FOREGROUND_BLUE,
	Purple = FOREGROUND_RED | FOREGROUND_BLUE,
	Yellow = FOREGROUND_RED | FOREGROUND_GREEN,
	BrRed = FOREGROUND_RED | FOREGROUND_INTENSITY,
	BrGreen = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	BrBlue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BrCyan = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BrPurple = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BrYellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
};

enum Direction {
	UP,
	RIGHT,
	BOT,
	LEFT,
	STOP
};

enum TankType {
	REGULAR,
	FAST,
	ARMORED
};

enum GunType {
	SINGLESHOT,
	FASTSHOT,
	DOUBLESHOT,
	STRONGSHOT
};

enum BonusType {
	STAR,
	BOMB,
	HELMET,
	TIME
};

enum WallType {
	BRICK = 1,
	WATER = 2,
	GRASS = 3,
	STEEL = 4,
	ICE = 5,
	BASE = 6,
	BASEBRICK = 7
};

enum ObjectType {
	CHARACTERPL = 50,
	CHARACTEREN = 51,
	BULLET = 55,
	BONUS = 60
};

enum BulletPower {
	STANDART = 25,
	HIGH = 50
};

enum BulletOwner {
	PLAYER,
	ENEMY
};

enum Buttons {
	UPKEY,
	DOWNKEY,
	RIGHTKEY,
	LEFTKEY,
	ESCKEY,
	SPACEKEY,
	RETURNKEY,
	RESTARTKEY,
	NOKEY
};